version: '3.1'

volumes:
  geth:
    driver: local

services:
  geth:
    image: ethereum/client-go:v1.10.11
    restart: always
    command:
      - --syncmode=full
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.api=web3,eth,net
      - --datadir=/data/ethereum
      - --ethash.dagdir=/data/ethereum/.ethash
      - --ipcdisable
    volumes:
      - geth:/data
